### ISSUE TITLE
Setting environment variables

### ISSUE THREAD

**Issue by sjurgis** [floyd-fuh/AFL_GCJ_Fuzzing_Simple#1]
I had to run `export AFL_GCJ=/usr/local/bin/gcj-6` to get paths correctly.

**Comment by floyd-fuh** [comment]
Hi sjurgis, sorry but AFL_GCJ is never defined in my code here. I'm unsure, but maybe you are referring to specifying https://github.com/mcarpenter/afl/blob/master/docs/env_variables.txt#L35  however, this is dependent on a) the way you install afl and b) probably your linux distro. It worked out of the box for an Ubuntu 16, so if you give me more information and details and especially which linux distro and version you are using, I can include it in the README.

**Comment by sjurgis** [comment]
Ah yes, this was for OS X. And the path is for the afl, not your code.

And just as you've mentioned, GCJ-6 doesn't compile. Seems this is a known issue since 2004 or so, you can't even get Hello World.

**Comment by floyd-fuh** [comment]
I see. Nice to hear I'm not the only one having issues using GCJ.
